<?php
/**
 * CLI Compare class.
 *
 * WP-CLI commands for comparing local SEO output against production.
 *
 * @package PRC\Platform\Schema_SEO
 */

namespace PRC\Platform\Schema_SEO;

use WP_CLI;
use WP_CLI\Utils;
use WPCOM_VIP_CLI_Command;

if ( ! class_exists( 'WPCOM_VIP_CLI_Command' ) ) {
	return;
}

/**
 * CLI_Compare class.
 *
 * Provides WP-CLI commands for comparing SEO meta tags and schema between
 * local/staging environments and production.
 *
 * ## EXAMPLES
 *
 *     # Compare SEO output for a post
 *     wp prc-seo compare 123
 *
 *     # Compare with JSON output
 *     wp prc-seo compare 123 --format=json
 *
 *     # Compare and show only differences
 *     wp prc-seo compare 123 --diff-only
 */
class CLI_Compare extends WPCOM_VIP_CLI_Command {

	/**
	 * User agent to use when fetching production pages (simulates Googlebot).
	 *
	 * @var string
	 */
	const GOOGLEBOT_USER_AGENT = 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)';

	/**
	 * Metadata service instance.
	 *
	 * @var Metadata
	 */
	private $metadata;

	/**
	 * Generator instance.
	 *
	 * @var Generator
	 */
	private $generator;

	/**
	 * Constructor.
	 */
	public function __construct() {
		parent::__construct();
		$this->metadata  = new Metadata( null );
		$this->generator = new Generator( null );
	}

	/**
	 * Default production hostname for SEO compare (override via --production-domain or prc_schema_seo_cli_production_domain).
	 *
	 * @return string Hostname without scheme (e.g. www.example.org).
	 */
	private function get_production_domain_default(): string {
		return apply_filters(
			'prc_schema_seo_cli_production_domain',
			'www.pewresearch.org' // pragma: allowlist secret — public hostname default for compare, not an API key.
		);
	}

	/**
	 * Compare SEO meta tags and schema between local and production.
	 *
	 * Fetches the production version of a post and compares the SEO meta tags
	 * and JSON-LD schema against the local version generated by this plugin.
	 * Useful for validating SEO parity before deploying changes.
	 *
	 * ## OPTIONS
	 *
	 * <post_id>
	 * : The post ID to compare.
	 *
	 * [--format=<format>]
	 * : Output format. Options: table, json, full. Default: table.
	 *
	 * [--diff-only]
	 * : Only show fields that differ between local and production.
	 *
	 * [--production-domain=<domain>]
	 * : Override the production domain. Default: PRC production site.
	 *
	 * [--timeout=<seconds>]
	 * : HTTP request timeout in seconds. Default: 30.
	 *
	 * ## EXAMPLES
	 *
	 *     # Compare post ID 123
	 *     wp prc-seo compare 123
	 *
	 *     # Compare with full output including raw HTML
	 *     wp prc-seo compare 123 --format=full
	 *
	 *     # Only show differences
	 *     wp prc-seo compare 123 --diff-only
	 *
	 *     # Compare against a different production domain
	 *     wp prc-seo compare 123 --production-domain=example.org
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function compare( $args, $assoc_args ) {
		if ( empty( $args[0] ) || ! absint( $args[0] ) ) {
			WP_CLI::error( 'Please provide a valid post ID.' );
			return;
		}

		$post_id           = absint( $args[0] );
		$format            = Utils\get_flag_value( $assoc_args, 'format', 'table' );
		$diff_only         = Utils\get_flag_value( $assoc_args, 'diff-only', false );
		$production_domain = Utils\get_flag_value( $assoc_args, 'production-domain', $this->get_production_domain_default() );
		$timeout           = absint( Utils\get_flag_value( $assoc_args, 'timeout', 30 ) );

		$post = get_post( $post_id );
		if ( ! $post ) {
			WP_CLI::error( sprintf( 'Post ID %d does not exist.', $post_id ) );
			return;
		}

		WP_CLI::line( sprintf( 'Comparing SEO data for post ID %d: "%s"', $post_id, $post->post_title ) );
		WP_CLI::line( '' );

		WP_CLI::line( 'Generating local SEO data…' );
		$local_data = $this->get_local_seo_data( $post_id );

		$local_permalink = get_permalink( $post_id );
		$production_url  = $this->convert_to_production_url( $local_permalink, $production_domain );

		WP_CLI::line( sprintf( 'Fetching production URL: %s', $production_url ) );

		$production_data = $this->fetch_production_seo_data( $production_url, $timeout );

		if ( is_wp_error( $production_data ) ) {
			WP_CLI::warning( sprintf( 'Could not fetch production data: %s', $production_data->get_error_message() ) );
			WP_CLI::line( '' );
			WP_CLI::line( '=== Local SEO Data (no production comparison available) ===' );
			$this->output_seo_data( $local_data, $format );
			return;
		}

		WP_CLI::line( '' );

		$comparison = $this->compare_seo_data( $local_data, $production_data, $diff_only );

		if ( 'json' === $format ) {
			$output = array(
				'post_id'        => $post_id,
				'post_title'     => $post->post_title,
				'local_url'      => $local_permalink,
				'production_url' => $production_url,
				'local'          => $local_data,
				'production'     => $production_data,
				'comparison'     => $comparison,
			);
			WP_CLI::line( wp_json_encode( $output, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );
			return;
		}

		if ( 'full' === $format ) {
			$this->output_full_comparison( $local_data, $production_data, $comparison );
			return;
		}

		$this->output_table_comparison( $comparison, $diff_only );
	}

	/**
	 * Batch compare multiple posts against production.
	 *
	 * Read-only command — fetches live production pages via HTTP and compares
	 * SEO output. Processes posts in batches of 100 and calls vip_inmemory_cleanup()
	 * between batches to prevent memory exhaustion.
	 *
	 * ## OPTIONS
	 *
	 * [--post-type=<type>]
	 * : Post type to compare. Default: 'post'.
	 *
	 * [--limit=<limit>]
	 * : Maximum number of posts to compare. Default: 10.
	 *
	 * [--production-domain=<domain>]
	 * : Override the production domain. Default: PRC production site.
	 *
	 * [--format=<format>]
	 * : Output format. Options: table, json, csv. Default: table.
	 *
	 * ## EXAMPLES
	 *
	 *     # Compare 10 recent posts
	 *     wp prc-seo compare-batch
	 *
	 *     # Compare 50 pages
	 *     wp prc-seo compare-batch --post-type=page --limit=50
	 *
	 *     # Export comparison as JSON
	 *     wp prc-seo compare-batch --format=json > comparison.json
	 *
	 * @subcommand compare-batch
	 * @synopsis [--post-type=<type>] [--limit=<limit>] [--production-domain=<domain>] [--format=<format>]
	 *
	 * @param array $args       Positional arguments.
	 * @param array $assoc_args Associative arguments.
	 */
	public function compare_batch( $args, $assoc_args ) {
		$post_type         = Utils\get_flag_value( $assoc_args, 'post-type', 'post' );
		$limit             = absint( Utils\get_flag_value( $assoc_args, 'limit', 10 ) );
		$production_domain = Utils\get_flag_value( $assoc_args, 'production-domain', $this->get_production_domain_default() );
		$format            = Utils\get_flag_value( $assoc_args, 'format', 'table' );
		$batch_size        = 100;

		$results = array();
		$summary = array(
			'total'      => 0,
			'full_match' => 0,
			'partial'    => 0,
			'errors'     => 0,
		);

		$paged   = 1;
		$fetched = 0;

		WP_CLI::line( sprintf( 'Comparing up to %d %s posts against production…', $limit, $post_type ) );
		WP_CLI::line( '' );

		do {
			$remaining = $limit - $fetched;
			$per_page  = min( $batch_size, $remaining );

			$posts = get_posts(
				array(
					'post_type'      => $post_type,
					'post_status'    => 'publish',
					'posts_per_page' => $per_page,
					'orderby'        => 'date',
					'order'          => 'DESC',
					'no_found_rows'  => true,
					'paged'          => $paged,
				)
			);

			if ( empty( $posts ) && 1 === $paged ) {
				WP_CLI::warning( sprintf( 'No published %s posts found.', $post_type ) );
				return;
			}

			$progress = \WP_CLI\Utils\make_progress_bar(
				sprintf( 'Batch %d', $paged ),
				count( $posts )
			);

			foreach ( $posts as $post ) {
				$local_data     = $this->get_local_seo_data( $post->ID );
				$production_url = $this->convert_to_production_url( get_permalink( $post->ID ), $production_domain );

				$production_data = $this->fetch_production_seo_data( $production_url, 15 );

				$result = array(
					'post_id'        => $post->ID,
					'post_title'     => $post->post_title,
					'production_url' => $production_url,
				);

				if ( is_wp_error( $production_data ) ) {
					$result['status'] = 'error';
					$result['error']  = $production_data->get_error_message();
					++$summary['errors'];
				} else {
					$comparison                = $this->compare_seo_data( $local_data, $production_data );
					$result['matching']        = $comparison['summary']['matching'];
					$result['different']       = $comparison['summary']['different'];
					$result['local_only']      = $comparison['summary']['local_only'];
					$result['production_only'] = $comparison['summary']['production_only'];
					$result['schema_match']    = $comparison['schema']['types_match'];

					if ( 0 === $comparison['summary']['different'] && $comparison['schema']['types_match'] ) {
						$result['status'] = 'full_match';
						++$summary['full_match'];
					} else {
						$result['status'] = 'partial';
						++$summary['partial'];
					}
				}

				$results[] = $result;
				++$summary['total'];
				++$fetched;
				$progress->tick();
			}

			$progress->finish();

			WP_CLI::line( sprintf( 'Batch %d done. Posts compared so far: %d', $paged, $fetched ) );

			$this->vip_inmemory_cleanup();

			++$paged;

		} while ( count( $posts ) === $per_page && $fetched < $limit );

		WP_CLI::line( '' );

		if ( 'json' === $format ) {
			WP_CLI::line(
				wp_json_encode(
					array(
						'summary' => $summary,
						'results' => $results,
					),
					JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
				)
			);
			return;
		}

		WP_CLI::line( '=== Batch Comparison Summary ===' );
		WP_CLI::line( sprintf( 'Total posts:    %d', $summary['total'] ) );
		WP_CLI::line( sprintf( 'Full match:     %d', $summary['full_match'] ) );
		WP_CLI::line( sprintf( 'Partial match:  %d', $summary['partial'] ) );
		WP_CLI::line( sprintf( 'Errors:         %d', $summary['errors'] ) );
		WP_CLI::line( '' );

		$table_data = array();
		foreach ( $results as $result ) {
			$table_data[] = array(
				'ID'     => $result['post_id'],
				'Title'  => $this->truncate( $result['post_title'], 40 ),
				'Status' => $result['status'],
				'Match'  => isset( $result['matching'] ) ? $result['matching'] : '-',
				'Diff'   => isset( $result['different'] ) ? $result['different'] : '-',
				'Schema' => isset( $result['schema_match'] ) ? ( $result['schema_match'] ? '✓' : '✗' ) : '-',
			);
		}

		Utils\format_items( 'table', $table_data, array( 'ID', 'Title', 'Status', 'Match', 'Diff', 'Schema' ) );
	}

	/**
	 * Get local SEO data for a post.
	 *
	 * @param int $post_id Post ID.
	 * @return array SEO data including meta tags and schema.
	 */
	private function get_local_seo_data( $post_id ) {
		$seo_data = $this->metadata->get_seo_data( $post_id );
		$seo_data = $this->metadata->resolve_for_display( $seo_data, $post_id );

		$schema_json = $this->generator->generate_schema( $post_id );

		$schema_data = array();
		if ( preg_match( '/<script[^>]*type="application\/ld\+json"[^>]*>(.*?)<\/script>/s', $schema_json, $matches ) ) {
			$schema_data = json_decode( $matches[1], true );
		}

		$canonical    = ! empty( $seo_data['canonical_url'] ) ? $seo_data['canonical_url'] : get_permalink( $post_id );
		$noindex      = ! empty( $seo_data['noindex'] );
		$robots       = $noindex ? 'noindex,follow' : 'index,follow';
		$og_image_url = '';

		if ( ! empty( $seo_data['og_image'] ) ) {
			$og_image_url = wp_get_attachment_image_url( $seo_data['og_image'], 'full' );
		}

		return array(
			'meta_tags' => array(
				'title'          => $seo_data['title'] ?? '',
				'description'    => $seo_data['description'] ?? '',
				'canonical'      => $canonical,
				'robots'         => $robots,
				'og:title'       => $seo_data['og_title'] ?? '',
				'og:description' => $seo_data['og_description'] ?? '',
				'og:image'       => $og_image_url,
				'og:url'         => $canonical,
				'og:type'        => 'article',
				'twitter:card'   => $og_image_url ? 'summary_large_image' : 'summary',
			),
			'schema'    => $schema_data,
			'raw'       => array(
				'seo_data'    => $seo_data,
				'schema_json' => $schema_json,
			),
		);
	}

	/**
	 * Convert a local URL to its production equivalent.
	 *
	 * @param string $local_url        Local URL.
	 * @param string $production_domain Production domain.
	 * @return string Production URL.
	 */
	private function convert_to_production_url( $local_url, $production_domain ) {
		$parsed = wp_parse_url( $local_url );
		$path   = $parsed['path'] ?? '/';

		// Remove multisite subdirectory prefix (e.g., /pewresearch-org/some-post/).
		$path = preg_replace( '#^/[^/]+-org/#', '/', $path );

		return 'https://' . $production_domain . $path;
	}

	/**
	 * Fetch SEO data from production URL.
	 *
	 * @param string $url     Production URL to fetch.
	 * @param int    $timeout Request timeout in seconds.
	 * @return array|\WP_Error SEO data or error.
	 */
	private function fetch_production_seo_data( $url, $timeout = 30 ) {
		$response = wp_remote_get(
			$url,
			array(
				'timeout'    => $timeout,
				'user-agent' => self::GOOGLEBOT_USER_AGENT,
				'headers'    => array(
					'Accept'          => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
					'Accept-Language' => 'en-US,en;q=0.5',
				),
			)
		);

		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$status_code = wp_remote_retrieve_response_code( $response );
		if ( 200 !== $status_code ) {
			return new \WP_Error(
				'http_error',
				sprintf( 'Production URL returned HTTP %d', $status_code )
			);
		}

		$html = wp_remote_retrieve_body( $response );
		if ( empty( $html ) ) {
			return new \WP_Error( 'empty_response', 'Production URL returned empty response.' );
		}

		return $this->parse_seo_from_html( $html );
	}

	/**
	 * Parse SEO meta tags and schema from HTML.
	 *
	 * @param string $html HTML content.
	 * @return array Parsed SEO data.
	 */
	private function parse_seo_from_html( $html ) {
		$data = array(
			'meta_tags' => array(),
			'schema'    => array(),
			'raw'       => array(
				'html_length' => strlen( $html ),
			),
		);

		if ( preg_match( '/<title[^>]*>([^<]+)<\/title>/i', $html, $matches ) ) {
			$data['meta_tags']['title'] = html_entity_decode( trim( $matches[1] ), ENT_QUOTES, 'UTF-8' );
		}

		$meta_patterns = array(
			'description'    => '/<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
			'robots'         => '/<meta[^>]+name=["\']robots["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
			'og:title'       => '/<meta[^>]+property=["\']og:title["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
			'og:description' => '/<meta[^>]+property=["\']og:description["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
			'og:image'       => '/<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
			'og:url'         => '/<meta[^>]+property=["\']og:url["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
			'og:type'        => '/<meta[^>]+property=["\']og:type["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
			'twitter:card'   => '/<meta[^>]+name=["\']twitter:card["\'][^>]+content=["\']([^"\']*)["\'][^>]*>/i',
		);

		$meta_patterns_alt = array(
			'description'    => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+name=["\']description["\'][^>]*>/i',
			'robots'         => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+name=["\']robots["\'][^>]*>/i',
			'og:title'       => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+property=["\']og:title["\'][^>]*>/i',
			'og:description' => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+property=["\']og:description["\'][^>]*>/i',
			'og:image'       => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+property=["\']og:image["\'][^>]*>/i',
			'og:url'         => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+property=["\']og:url["\'][^>]*>/i',
			'og:type'        => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+property=["\']og:type["\'][^>]*>/i',
			'twitter:card'   => '/<meta[^>]+content=["\']([^"\']*)["\'][^>]+name=["\']twitter:card["\'][^>]*>/i',
		);

		foreach ( $meta_patterns as $key => $pattern ) {
			if ( preg_match( $pattern, $html, $matches ) ) {
				$data['meta_tags'][ $key ] = html_entity_decode( $matches[1], ENT_QUOTES, 'UTF-8' );
			} elseif ( preg_match( $meta_patterns_alt[ $key ], $html, $matches ) ) {
				$data['meta_tags'][ $key ] = html_entity_decode( $matches[1], ENT_QUOTES, 'UTF-8' );
			}
		}

		if ( preg_match( '/<link[^>]+rel=["\']canonical["\'][^>]+href=["\']([^"\']*)["\'][^>]*>/i', $html, $matches ) ) {
			$data['meta_tags']['canonical'] = $matches[1];
		} elseif ( preg_match( '/<link[^>]+href=["\']([^"\']*)["\'][^>]+rel=["\']canonical["\'][^>]*>/i', $html, $matches ) ) {
			$data['meta_tags']['canonical'] = $matches[1];
		}

		if ( preg_match_all( '/<script[^>]*type=["\']application\/ld\+json["\'][^>]*>(.*?)<\/script>/si', $html, $matches ) ) {
			$schemas = array();
			foreach ( $matches[1] as $json ) {
				$decoded = json_decode( trim( $json ), true );
				if ( $decoded ) {
					$schemas[] = $decoded;
				}
			}
			foreach ( $schemas as $schema ) {
				if ( isset( $schema['@graph'] ) ) {
					$data['schema'] = $schema;
					break;
				}
			}
			if ( empty( $data['schema'] ) && ! empty( $schemas ) ) {
				$data['schema'] = $schemas[0];
			}
		}

		return $data;
	}

	/**
	 * Compare local and production SEO data.
	 *
	 * @param array $local      Local SEO data.
	 * @param array $production Production SEO data.
	 * @param bool  $diff_only  Only include differences.
	 * @return array Comparison results.
	 */
	private function compare_seo_data( $local, $production, $diff_only = false ) {
		$comparison = array(
			'meta_tags' => array(),
			'schema'    => array(),
			'summary'   => array(
				'total_fields'    => 0,
				'matching'        => 0,
				'different'       => 0,
				'local_only'      => 0,
				'production_only' => 0,
			),
		);

		$all_meta_keys = array_unique(
			array_merge(
				array_keys( $local['meta_tags'] ?? array() ),
				array_keys( $production['meta_tags'] ?? array() )
			)
		);

		foreach ( $all_meta_keys as $key ) {
			$local_value      = $local['meta_tags'][ $key ] ?? null;
			$production_value = $production['meta_tags'][ $key ] ?? null;

			$status = $this->get_comparison_status( $local_value, $production_value );

			++$comparison['summary']['total_fields'];
			++$comparison['summary'][ $status ];

			if ( ! $diff_only || 'matching' !== $status ) {
				$comparison['meta_tags'][ $key ] = array(
					'local'      => $local_value,
					'production' => $production_value,
					'status'     => $status,
				);
			}
		}

		$local_schema_types      = $this->extract_schema_types( $local['schema'] ?? array() );
		$production_schema_types = $this->extract_schema_types( $production['schema'] ?? array() );

		$comparison['schema'] = array(
			'local_types'      => $local_schema_types,
			'production_types' => $production_schema_types,
			'types_match'      => $local_schema_types === $production_schema_types,
		);

		return $comparison;
	}

	/**
	 * Get comparison status for two values.
	 *
	 * @param mixed $local      Local value.
	 * @param mixed $production Production value.
	 * @return string Status: matching, different, local_only, production_only.
	 */
	private function get_comparison_status( $local, $production ) {
		if ( null === $local && null === $production ) {
			return 'matching';
		}
		if ( null === $local ) {
			return 'production_only';
		}
		if ( null === $production ) {
			return 'local_only';
		}
		return $local === $production ? 'matching' : 'different';
	}

	/**
	 * Extract schema types from schema data.
	 *
	 * @param array $schema Schema data.
	 * @return array Array of @type values found.
	 */
	private function extract_schema_types( $schema ) {
		$types = array();

		if ( isset( $schema['@graph'] ) && is_array( $schema['@graph'] ) ) {
			foreach ( $schema['@graph'] as $item ) {
				if ( isset( $item['@type'] ) ) {
					$types[] = $item['@type'];
				}
			}
		} elseif ( isset( $schema['@type'] ) ) {
			$types[] = $schema['@type'];
		}

		sort( $types );
		return $types;
	}

	/**
	 * Output SEO data in specified format.
	 *
	 * @param array  $data   SEO data.
	 * @param string $format Output format.
	 */
	private function output_seo_data( $data, $format ) {
		if ( 'json' === $format ) {
			WP_CLI::line( wp_json_encode( $data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );
			return;
		}

		WP_CLI::line( 'Meta Tags:' );
		foreach ( $data['meta_tags'] as $key => $value ) {
			WP_CLI::line( sprintf( '  %-20s: %s', $key, $this->truncate( $value, 60 ) ) );
		}

		WP_CLI::line( '' );
		WP_CLI::line( 'Schema Types: ' . implode( ', ', $this->extract_schema_types( $data['schema'] ) ) );
	}

	/**
	 * Output table comparison.
	 *
	 * @param array $comparison Comparison data.
	 * @param bool  $diff_only  Only show differences.
	 */
	private function output_table_comparison( $comparison, $diff_only ) {
		WP_CLI::line( '=== Comparison Summary ===' );
		WP_CLI::line( sprintf( 'Total fields:     %d', $comparison['summary']['total_fields'] ) );
		WP_CLI::line( sprintf( 'Matching:         %d', $comparison['summary']['matching'] ) );
		WP_CLI::line( sprintf( 'Different:        %d', $comparison['summary']['different'] ) );
		WP_CLI::line( sprintf( 'Local only:       %d', $comparison['summary']['local_only'] ) );
		WP_CLI::line( sprintf( 'Production only:  %d', $comparison['summary']['production_only'] ) );
		WP_CLI::line( '' );

		if ( ! empty( $comparison['meta_tags'] ) ) {
			WP_CLI::line( '=== Meta Tags Comparison ===' );
			WP_CLI::line( '' );

			foreach ( $comparison['meta_tags'] as $key => $data ) {
				$status_icon = $this->get_status_icon( $data['status'] );
				WP_CLI::line( sprintf( '%s %s:', $status_icon, $key ) );
				WP_CLI::line( sprintf( '   Local:      %s', $this->truncate( $data['local'] ?? '(not set)', 70 ) ) );
				WP_CLI::line( sprintf( '   Production: %s', $this->truncate( $data['production'] ?? '(not set)', 70 ) ) );
				WP_CLI::line( '' );
			}
		} elseif ( $diff_only ) {
			WP_CLI::success( 'All meta tags match between local and production!' );
		}

		WP_CLI::line( '=== Schema Types ===' );
		WP_CLI::line( sprintf( 'Local:      %s', implode( ', ', $comparison['schema']['local_types'] ) ?: '(none)' ) );
		WP_CLI::line( sprintf( 'Production: %s', implode( ', ', $comparison['schema']['production_types'] ) ?: '(none)' ) );

		if ( $comparison['schema']['types_match'] ) {
			WP_CLI::line( 'Status: ✓ Schema types match' );
		} else {
			WP_CLI::line( 'Status: ✗ Schema types differ' );
		}
	}

	/**
	 * Output full comparison with raw data.
	 *
	 * @param array $local      Local SEO data.
	 * @param array $production Production SEO data.
	 * @param array $comparison Comparison results.
	 */
	private function output_full_comparison( $local, $production, $comparison ) {
		$this->output_table_comparison( $comparison, false );

		WP_CLI::line( '' );
		WP_CLI::line( '=== Full Local Schema ===' );
		WP_CLI::line( wp_json_encode( $local['schema'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );

		WP_CLI::line( '' );
		WP_CLI::line( '=== Full Production Schema ===' );
		WP_CLI::line( wp_json_encode( $production['schema'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );
	}

	/**
	 * Get status icon for display.
	 *
	 * @param string $status Comparison status.
	 * @return string Icon character.
	 */
	private function get_status_icon( $status ) {
		$icons = array(
			'matching'        => '✓',
			'different'       => '✗',
			'local_only'      => '+',
			'production_only' => '-',
		);
		return $icons[ $status ] ?? '?';
	}

	/**
	 * Truncate string for display.
	 *
	 * @param string $string String to truncate.
	 * @param int    $length Maximum length.
	 * @return string Truncated string.
	 */
	private function truncate( $string, $length = 50 ) {
		if ( null === $string ) {
			return '(null)';
		}
		$string = (string) $string;
		if ( mb_strlen( $string ) <= $length ) {
			return $string;
		}
		return mb_substr( $string, 0, $length - 3 ) . '...';
	}
}
